# Generated by Django 4.2.7 on 2025-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='technologies/'),
        ),
    ]
