# Generated by Django 4.2.7 on 2025-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_technology_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='personal',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
