# Generated by Django 4.2.7 on 2025-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_personal_cv_link_personal_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
