# Generated by Django 4.2.7 on 2025-10-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_personal_cv_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='cv',
        ),
        migrations.AlterField(
            model_name='personal',
            name='cv_link',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
